# Основные настройки
listening-port=3478
fingerprint
lt-cred-mech

# Авторизация (логин:пароль)
user=present_user:present_secret_2024

# Домен/реалм
realm=presentation.tatcon.ru

# Логирование
log-file=/var/tmp/turn.log
simple-log

# Безопасность
no-stdout-log
no-multicast-peers
no-tlsv1
no-tlsv1.1

# Диапазон портов для передачи данных
min-port=49152
max-port=65535
